apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infrastructure/kubernetes/*

build:
  local:
    push: false
  artifacts:
    - image: eriklysne/home
      context: .
      docker:
        dockerfile: /microservices/home/Dockerfile
      sync:
        manual:
          - src: './microservices/home/src/**/*.ts'
            dest: .
          