version: '3.8'
services:

  postgress:
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - postgres:/var/lib/postresql/data
    ports:
      - '5432:5432'

volumes:
  postgres: